import type { VocabCard } from "./types";

const ROWS: [string, string, string, string][] = [
  ["invoice", "n.", "发票", "Please send the invoice to accounting."],
  ["shipment", "n.", "一批货物", "The shipment arrives on Thursday."],
  ["deadline", "n.", "截止日期", "The registration deadline is November 23."],
  ["refund", "n.", "退款", "Rush fees are not eligible for a refund."],
  ["venue", "n.", "场地", "The venue has moved to Room 210."],
  ["postpone", "v.", "推迟", "We postponed the client meeting."],
  ["confirm", "v.", "确认", "Please confirm your seat by Friday."],
  ["attach", "v.", "附上", "I attached the revised schedule."],
  ["inquire", "v.", "询问", "She called to inquire about the course."],
  ["available", "adj.", "有空的；可得到的", "The manager is available after 3 p.m."],
  ["mandatory", "adj.", "必须的", "Safety training is mandatory."],
  ["tentative", "adj.", "暂定的", "The date is still tentative."],
  ["promptly", "adv.", "立即", "Please reply promptly."],
  ["approximately", "adv.", "大约", "The repair takes approximately two hours."],
  ["inventory", "n.", "库存", "Warehouse inventory is lower than expected."],
  ["receipt", "n.", "收据", "Keep the receipt for reimbursement."],
  ["overdue", "adj.", "逾期的", "The payment is three days overdue."],
  ["waiver", "n.", "免除", "A fee waiver applies to the first transfer."],
  ["agenda", "n.", "议程", "The agenda was sent yesterday."],
  ["applicant", "n.", "申请人", "Each applicant must bring identification."],
  ["approve", "v.", "批准", "The director approved the budget."],
  ["arrange", "v.", "安排", "Ms. Chen arranged the interviews."],
  ["attend", "v.", "参加", "All supervisors will attend the briefing."],
  ["budget", "n.", "预算", "The revised budget will be discussed Friday."],
  ["cancel", "v.", "取消", "They canceled the morning session."],
  ["candidate", "n.", "候选人", "The candidate accepted the offer."],
  ["complaint", "n.", "投诉", "We received a complaint about the delay."],
  ["contract", "n.", "合同", "Both sides signed the contract."],
  ["department", "n.", "部门", "Contact the shipping department."],
  ["deliver", "v.", "送达", "The printer will deliver the brochures."],
  ["discount", "n.", "折扣", "Members receive a ten percent discount."],
  ["distribute", "v.", "分发", "Please distribute the handbook."],
  ["efficient", "adj.", "有效率的", "The new process is more efficient."],
  ["estimate", "n.", "估算", "The estimate does not include tax."],
  ["expand", "v.", "扩大", "The store will expand next spring."],
  ["expense", "n.", "费用", "Travel expenses must be approved."],
  ["facility", "n.", "设施", "The facility closes at 8 p.m."],
  ["headquarters", "n.", "总部", "Headquarters is in Shanghai."],
  ["implement", "v.", "实施", "We will implement the policy on Monday."],
  ["inspection", "n.", "检查", "The inspection is scheduled for Tuesday."],
  ["itinerary", "n.", "行程", "Your itinerary is attached."],
  ["logistics", "n.", "物流", "Logistics confirmed the pickup time."],
  ["maintenance", "n.", "维护", "Elevator maintenance begins at noon."],
  ["notify", "v.", "通知", "We will notify you of any change."],
  ["obligation", "n.", "义务", "Payment is a contractual obligation."],
  ["option", "n.", "选项；选择", "Remote work is an option on Fridays."],
  ["participate", "v.", "参加", "Interns may participate in the workshop."],
  ["policy", "n.", "政策", "The new policy replaces the old one."],
  ["priority", "n.", "优先事项", "Safety is the first priority."],
  ["procedure", "n.", "流程", "Follow the checkout procedure."],
  ["proposal", "n.", "提案", "The proposal needs two signatures."],
  ["purchase", "v.", "购买", "The office purchased new chairs."],
  ["qualify", "v.", "有资格", "Only full-time staff qualify for the bonus."],
  ["quote", "n.", "报价", "Please send a written quote."],
  ["recruit", "v.", "招聘", "The firm will recruit ten analysts."],
  ["refundable", "adj.", "可退款的", "The deposit is not refundable."],
  ["regulation", "n.", "规定", "The regulation takes effect in January."],
  ["reimburse", "v.", "报销", "The company will reimburse taxi fares."],
  ["reminder", "n.", "提醒", "This is a reminder about the survey."],
  ["renew", "v.", "续期", "Remember to renew your badge."],
  ["requirement", "n.", "要求", "A photo is a registration requirement."],
  ["reservation", "n.", "预订", "The reservation is under your name."],
  ["resolve", "v.", "解决", "We resolved the billing error."],
  ["restrict", "v.", "限制", "Access is restricted to employees."],
  ["revenue", "n.", "收入", "Quarterly revenue exceeded the forecast."],
  ["schedule", "v.", "安排时间", "Schedule the review before Thursday."],
  ["shortage", "n.", "短缺", "A parts shortage delayed production."],
  ["submit", "v.", "提交", "Submit the form by the end of the day."],
  ["supplier", "n.", "供应商", "The supplier changed the delivery date."],
  ["survey", "n.", "调查", "The survey takes about five minutes."],
  ["temporary", "adj.", "临时的", "A temporary lounge is in Room 210."],
  ["terminate", "v.", "终止", "Either party may terminate the contract."],
];

export const VOCAB: VocabCard[] = ROWS.map(([word, pos, meaning, example], index) => ({
  id: `v${index + 1}`,
  word,
  pos,
  meaning,
  example,
}));

export const VOCAB_PER_DAY = 12;
